//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;

[assembly: System.Reflection.AssemblyCompanyAttribute("FinanceTracker.Application")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+25aee847bb3ba54d3335cbfcf5252bb1cebd457a")]
[assembly: System.Reflection.AssemblyProductAttribute("FinanceTracker.Application")]
[assembly: System.Reflection.AssemblyTitleAttribute("FinanceTracker.Application")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

[assembly: InternalsVisibleTo("FinanceTracker.Tests.Unit")]
